### ISSUE TITLE
Is Core really necessary?

### ISSUE THREAD

**Issue by dmitriz** [srph/angularjs-structure-styleguide#7]
Great guide!

But isn't "Core" a sign of "weak philosophy"? :-)

Shouldn't they be either components of belong to states?

**Comment by srph** [comment]
Well, yes. You can think of the `/core/` directory as the shared stuff, like services, configs, and etc.

**Comment by dmitriz** [comment]
Wouldn't those be components rather than core?

**Comment by srph** [comment]
Sorry for that -- reusable directives go to components. It's better this way because the number of directives can get so many, especially for real-world application. And like I said, this was mainly motivated by ReactJS's architecture which is why I called it `components`. Technically, the folder contains and act like and are reusable components.
